[package]
name = "pancake-db"
version = "0.0.0"
authors = ["mwlon <m.w.loncaric@gmail.com>"]
edition = "2018"

[dependencies]
async-std = "1.9.0"
async-trait = "0.1.48"
futures = "0.3.12"
hyper = {version="0.14.9", features=["full"]}
pancake-db-idl = {path="../pancake-idl/rust", version="0.0.0"}
protobuf = {git="https://github.com/stepancheg/rust-protobuf"}
serde_json = "1.0.59"
serde = {version="1.0.117", features=["derive"]}
tokio = {version="1.2.0", features=["full"]}
tower = {version="0.4.6", features=["full"]}
tower-http = {version="0.1.1", features=["full"]}
warp = "0.3.1"
